version: '3.0'

volumes: 
  
  www:
    driver_opts: 
      type: none
      device: /web/www
      o: bind

  nginx_conf:
    driver_opts: 
      type: none
      device: /web/nginx
      o: bind
  
  mysql:
    driver_opts: 
      type: none
      device: /web/data/mysql
      o: bind

services: 

  proxy:
    image: nginx:stable-alpine
    labels: 
      name: web
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
    ports: 
    - '443:443'
    - '80:80'
    volumes: 
    - nginx_conf:/etc/nginx/conf.d
    - www:/www

  # mysql
  mysql:
    image: mariadb
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
    volumes: 
    - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      replicas: 0
    ports: 
    - 8080:80
    environment: 
    - PMA_HOST=mysql

  php7: 
    image: hermsi/alpine-fpm-php
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
    volumes: 
    - www:/www

  # php5:
  #   image: cytopia/php-fpm-5.6
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         memory: 500M
  #   volumes: 
  #   - www:/www
