version: '3.0'

volumes: 
  
  www:
    driver_opts: 
      type: none
      device: /docker/data/www
      o: bind

services: 

  proxy:
    image: nginx:stable-alpine
    labels: 
      name: nginx
    deploy:
      replicas: 1
    ports: 
    - '443:443'
    - '80:80'
    volumes: 
    - 'www:/var/www/html/:ro'
