FROM alpine as base
RUN set -xe && \
  sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
  apk add --no-cache git nodejs openssh && \
  echo finished

FROM alpine
WORKDIR /web
VOLUME [/web]
EXPOSE 24
COPY --from=base / /

COPY . /web
RUN npm i --production

